---
- name: Ensure that the selinux packages are installed
  tags: selinux
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: selinux_yum
  with_items:
    - libselinux-python
    - selinux-policy

- name: Applying selinux policy and state configurations
  tags: selinux
  become: true
  selinux:
    conf: "{{ selinux_conf }}"
    policy: "{{ selinux_policy }}"
    state: "{{ selinux_state }}"
  when: selinux_yum is success
...
